CORE_OBJECTS = [
    "KnowledgeObject","Source","Actor","Subject","Claim","Evidence","Policy","Profile","Case",
    "Analysis","AnalyticalMethod","AnalysisResult","ValidationRule","DecisionRight","ReviewRequest",
    "HumanDecision","ActionProposal","Action","CapabilityGrant","Decision","Event","ModelResource",
    "ProcessingEnvironment","Jurisdiction","Connector","AuditRecord"
]
CORE_ATTRIBUTES = [
    "id","type","source","author_or_actor","created_at","effective_from","effective_until","status",
    "classification","jurisdiction","region","provenance_status","authority","priority","applicability",
    "evidence_role","model_eligibility","processing_constraints","policy_version","derivation","confidence",
    "purpose","retention","analysis_method","outcome_disposition","decision_owner","executor"
]
CORE_RELATIONSHIPS = [
    "SUPPORTS","CONTRADICTS","QUALIFIES","CORROBORATES","DERIVES_FROM","SUPERSEDES","GOVERNS",
    "APPLIES_TO","DEPENDS_ON","OVERRIDES","RESTRICTS","REQUIRES","GENERATES","VALIDATES","TRIGGERS"
]
KNOWLEDGE_OPERATIONS = [
    "ALLOW","DENY","EXCLUDE","REQUIRE","PRIORITIZE","DEPRIORITIZE","DEFER_TO","OVERRIDE",
    "REQUIRE_CORROBORATION","ASSIGN_ROLE","QUARANTINE","EMBARGO","ISOLATE","RELEASE","SUPERSEDE",
    "EXPIRE","REVOKE","ARCHIVE","FILTER","SAMPLE","GROUP","AGGREGATE","SORT","LIMIT",
    "TRACE","VERIFY_SOURCE","REQUIRE_PROVENANCE","MARK_PROVENANCE"
]
ANALYSIS_OPERATIONS = [
    "COMPARE","CLASSIFY","SUMMARIZE","CALCULATE","SCORE","ESTIMATE","INFER","CORROBORATE","CHALLENGE",
    "VERIFY","NORMALIZE","WEIGHT","BALANCE","REQUIRE_SECOND_SOURCE","REQUIRE_VALIDATION",
    "REQUIRE_EXPLANATION","PRESERVE_CONFLICT","DO_NOT_INFER","LIMIT_INFERENCE","VALIDATE","REPROCESS"
]
ROUTING_OPERATIONS = [
    "ROUTE","REQUIRE_MODEL","DENY_MODEL","REQUIRE_REGION","DENY_REGION","LOCAL_ONLY","NO_FALLBACK",
    "REQUIRE_VALIDATED_VERSION"
]
CONTROL_OPERATIONS = ["CASE","SELECT","IF","WHEN","THEN","DO","ELSE","FOR_EACH","UNTIL","STOP","FALLBACK","EXCEPTION"]
DECISION_OPERATIONS = ["PERMIT","QUALIFY","BLOCK","ABSTAIN","ESCALATE","REQUIRE_REVIEW"]
CONSEQUENCE_OPERATIONS = ["INFORM","DECIDE","ACT","APPROVE","DENY_ACTION","MODIFY","CONSENT","REQUEST_EVIDENCE","DEFER","AUTHORIZE","EXECUTE"]
CORE_OPERATIONS = KNOWLEDGE_OPERATIONS + ANALYSIS_OPERATIONS + ROUTING_OPERATIONS + CONTROL_OPERATIONS + ["DECIDE"] + DECISION_OPERATIONS
DECISION_STATES = ["PERMITTED","QUALIFIED","BLOCKED","ABSTAINED","ESCALATED","AWAITING_REVIEW"]
DECISION_OPERATION_TO_STATE = {
    "PERMIT":"PERMITTED", "QUALIFY":"QUALIFIED", "BLOCK":"BLOCKED",
    "ABSTAIN":"ABSTAINED", "ESCALATE":"ESCALATED", "REQUIRE_REVIEW":"AWAITING_REVIEW"
}
CONSEQUENCE_DISPOSITIONS = ["INFORM","DECIDE","ACT"]
HUMAN_DECISIONS = ["APPROVE","DENY","MODIFY","CONSENT","REQUEST_EVIDENCE","DEFER","ESCALATE"]
ANALYSIS_STATES = ["READY","VERIFIED","QUALIFIED","INSUFFICIENT","AWAITING_VALIDATION","BLOCKED"]
FAILURE_REASON_CODES = [
    "INSUFFICIENT_EVIDENCE","POLICY_CONFLICT","NO_COMPLIANT_ROUTE","MISSING_ATTRIBUTE",
    "CONNECTOR_FAILURE","POLICY_PARSE_ERROR","PROVENANCE_UNRESOLVED","AUDIT_FAILURE",
    "ANALYSIS_METHOD_NOT_PERMITTED","ANALYSIS_VALIDATION_REQUIRED","ACTION_NOT_AUTHORIZED"
]
EVIDENCE_ROLES = ["GOVERNING","PRIMARY","CORROBORATING","SUPPLEMENTARY","CONTEXTUAL","CONTRADICTORY","EXCLUDED"]
DEFAULT_PRECEDENCE = [
    "legal_regulatory_sovereign","explicit_prohibitions_security","classification_processing_location",
    "lifecycle_restrictions","governing_authority","mandatory_evidence_human_review","case_specific",
    "organizational_defaults","priority_preferences","fallback"
]
GOVERNANCE_STAGES = ["KNOWLEDGE","ANALYSIS","CONSEQUENCE"]
